name: area_and_plot
description: "Bangladesh Land Area Calculator with Map Integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: any
  riverpod_annotation: any

  # Navigation
  go_router: any

  # Code Generation Annotations
  freezed_annotation: any
  json_annotation: any

  # Offline Database
  hive_flutter: any

  # Firebase & Auth
  firebase_core: any
  firebase_auth: any
  google_sign_in: any

  # Maps
  flutter_map: any
  latlong2: any

  # Permissions
  permission_handler: any

  # Utilities
  cupertino_icons: any
  intl: any
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

  # Code Generation
  build_runner: any
  riverpod_generator: any
  freezed: any
  json_serializable: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
